"""add indexes to profiles and matches

Revision ID: 1e05167235a8
Revises: 05b4f057001b
Create Date: 2026-05-10 12:57:47.273236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e05167235a8'
down_revision = '05b4f057001b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_location'))
        batch_op.drop_index(batch_op.f('ix_profiles_age'))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_matches_target_id'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))

    # ### end Alembic commands ###
