"""add 2fa fields to users

Revision ID: 551e0f583efa
Revises: d65030de4bb3
Create Date: 2026-05-08 10:47:37.368036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551e0f583efa'
down_revision = 'd65030de4bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
